// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3x09ClQx98rHi1pLANeX_dFrL22TRpg',
    appId: '1:994112219091:android:d63eb62bf2ffa48d7fb126',
    messagingSenderId: '994112219091',
    projectId: 'biological-324006',
    storageBucket: 'biological-324006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUj_idBA_lx0_xWOe2I1WEcKSY2VYhV68',
    appId: '1:994112219091:ios:1db8bf8dc3b2bce67fb126',
    messagingSenderId: '994112219091',
    projectId: 'biological-324006',
    storageBucket: 'biological-324006.appspot.com',
    androidClientId: '994112219091-5kou6an6tn22mge0tt7llvm4a6oim13i.apps.googleusercontent.com',
    iosClientId: '994112219091-26s6sla8vs99oa5761el3fqoe07hiroa.apps.googleusercontent.com',
    iosBundleId: 'tw.biological.app',
  );
}
